spring.application.name=TaxiTrajectory

server.port=8080

# data????????
# ????
taxi.data.path:classpath:data/*.txt

# ?????????if false, log in service layer will not output
# TODO: add log function for all service and inject enabled property
logging.service.enabled=true
