spring.application.name=TaxiTrajectory

server.port=8080

# data path
taxi.data.path:classpath:data/*.txt


# TODO: add log function for all service and inject enabled property
# logging for service layer, if false, log in service layer will not output
logging.service.enabled=true
# logging for repository layer, if false, log in repository layer will not output
logging.repository.enabled=false

# min trip points is needed in travelTimeService
trajectory.analysis.min_trip_points=2

# max time interval as a path
trajectory.analysis.segmentation.max_time_gap_minutes:30

# Cache Configuration for Taxi Data
# Maximum number of taxi trajectory entries to keep in memory cache
cache.taxi.maxSize=5000
# Evict entries after this many minutes of inactivity (last access)
cache.taxi.expireAfterAccessMinutes=60


# map properties and segment
map.bounds.minLongitude=116.0
map.bounds.minLatitude=39.7
map.bounds.maxLongitude=116.8
map.bounds.maxLatitude=40.2
map.gridSizeKM = 0.5



